name         'camptocamp-augeasfacter'
version      '0.0.1'
source       'https://github.com/camptocamp/puppet-augeasfacter'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp AugeasFacter Module'
description  'AugeasFacter Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-augeasfacter'
